apiVersion: v1
kind: Service
metadata:
  labels:
    app: pihole
  name: pihole
spec:  
  ports:
  - name: pihole-https    
    port: 80
    protocol: TCP
    targetPort: pihole-http
  - name: pihole-https    
    port: 443
    protocol: TCP
    targetPort: pihole-https
  - name: dns    
    port: 53
    protocol: TCP
    targetPort: dns
  selector:
    app: pihole
  sessionAffinity: None
  type: LoadBalancer